name: Run Unit Tests with Coverage

on: [push, pull_request]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up python
      uses: actions/setup-python@v3git
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install pytest pytest-cov
       
    - name: Run unit tests
      run: pytest --cov=your_module --cov-fail-under=90